# EVOLVER_STATE: 7
"""Autogenerated evolutionary module."""

APP_NAME = "reporting"
MODULE_ROLE = "selectors"
STATE_LABEL = "tilt"
FOCUS_VECTOR = "priority routing"
GUARD_RAIL = "load thresholds"
QUALITY_METRIC = "queue smoothness"
DELIVERY_STYLE = "dynamic"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
