# EVOLVER_STATE: 6
"""Autogenerated evolutionary module."""

APP_NAME = "reporting"
MODULE_ROLE = "selectors"
STATE_LABEL = "trace"
FOCUS_VECTOR = "audit granularity"
GUARD_RAIL = "event hashing"
QUALITY_METRIC = "trace fidelity"
DELIVERY_STYLE = "forensic"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
