# EVOLVER_STATE: 0
"""Autogenerated evolutionary module."""

APP_NAME = "support"
MODULE_ROLE = "selectors"
STATE_LABEL = "seed"
FOCUS_VECTOR = "baseline integrity"
GUARD_RAIL = "strict schema checks"
QUALITY_METRIC = "consistency ratio"
DELIVERY_STYLE = "conservative"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
