# EVOLVER_STATE: 1
"""Autogenerated evolutionary module."""

APP_NAME = "support"
MODULE_ROLE = "selectors"
STATE_LABEL = "draft"
FOCUS_VECTOR = "field expansion"
GUARD_RAIL = "type-aware casting"
QUALITY_METRIC = "coverage span"
DELIVERY_STYLE = "iterative"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
