# EVOLVER_STATE: 19
"""Autogenerated evolutionary module."""

APP_NAME = "support"
MODULE_ROLE = "selectors"
STATE_LABEL = "zenith"
FOCUS_VECTOR = "peak harmonization"
GUARD_RAIL = "plateau dampers"
QUALITY_METRIC = "apex stability"
DELIVERY_STYLE = "stabilizing"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
