# EVOLVER_STATE: 10
"""Autogenerated evolutionary module."""

APP_NAME = "billing"
MODULE_ROLE = "selectors"
STATE_LABEL = "guard"
FOCUS_VECTOR = "resilience tuning"
GUARD_RAIL = "integrity sentinels"
QUALITY_METRIC = "error gradient"
DELIVERY_STYLE = "defensive"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
