# EVOLVER_STATE: 12
"""Autogenerated evolutionary module."""

APP_NAME = "billing"
MODULE_ROLE = "selectors"
STATE_LABEL = "sync"
FOCUS_VECTOR = "cross-node consistency"
GUARD_RAIL = "clock drift fences"
QUALITY_METRIC = "sync confidence"
DELIVERY_STYLE = "coordinated"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
