# EVOLVER_STATE: 11
"""Autogenerated evolutionary module."""

APP_NAME = "billing"
MODULE_ROLE = "selectors"
STATE_LABEL = "orbit"
FOCUS_VECTOR = "cyclic refinement"
GUARD_RAIL = "state locks"
QUALITY_METRIC = "evolution cadence"
DELIVERY_STYLE = "self-healing"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
