# EVOLVER_STATE: 15
"""Autogenerated evolutionary module."""

APP_NAME = "inventory"
MODULE_ROLE = "selectors"
STATE_LABEL = "anchor"
FOCUS_VECTOR = "baseline recovery"
GUARD_RAIL = "rollback anchors"
QUALITY_METRIC = "stability rebound"
DELIVERY_STYLE = "grounded"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
