# EVOLVER_STATE: 17
"""Autogenerated evolutionary module."""

APP_NAME = "inventory"
MODULE_ROLE = "selectors"
STATE_LABEL = "spark"
FOCUS_VECTOR = "exploration bursts"
GUARD_RAIL = "blast radius limits"
QUALITY_METRIC = "novelty yield"
DELIVERY_STYLE = "experimental"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
