# EVOLVER_STATE: 18
"""Autogenerated evolutionary module."""

APP_NAME = "inventory"
MODULE_ROLE = "selectors"
STATE_LABEL = "lattice"
FOCUS_VECTOR = "mesh alignment"
GUARD_RAIL = "graph invariants"
QUALITY_METRIC = "topology health"
DELIVERY_STYLE = "structured"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
