# EVOLVER_STATE: 13
"""Autogenerated evolutionary module."""

APP_NAME = "orders"
MODULE_ROLE = "selectors"
STATE_LABEL = "weave"
FOCUS_VECTOR = "dependency braiding"
GUARD_RAIL = "ordering contracts"
QUALITY_METRIC = "link coherence"
DELIVERY_STYLE = "layered"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
