# EVOLVER_STATE: 5
"""Autogenerated evolutionary module."""

APP_NAME = "orders"
MODULE_ROLE = "selectors"
STATE_LABEL = "fuse"
FOCUS_VECTOR = "cross-module linkage"
GUARD_RAIL = "compatibility gates"
QUALITY_METRIC = "link score"
DELIVERY_STYLE = "composed"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
