# EVOLVER_STATE: 3
"""Autogenerated evolutionary module."""

APP_NAME = "orders"
MODULE_ROLE = "selectors"
STATE_LABEL = "pulse"
FOCUS_VECTOR = "activity balancing"
GUARD_RAIL = "bounded retries"
QUALITY_METRIC = "throughput signal"
DELIVERY_STYLE = "adaptive"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
