from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import math
import random
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RECIPES_PATH = ROOT / "automation" / "evolver" / "recipes.json"
MATRIX_PATH = ROOT / "automation" / "evolver" / "state_matrix.json"
RUNTIME_DIR = ROOT / ".evolver"
RUNTIME_STATE_PATH = RUNTIME_DIR / "runtime_state.json"
RUNTIME_HISTORY_PATH = RUNTIME_DIR / "history.json"
DASHBOARD_PATH = ROOT / "automation" / "evolver" / "DASHBOARD.md"
STATE_PATTERN = re.compile(r"^# EVOLVER_STATE: (\d+)$", re.MULTILINE)


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def load_json_or_default(path: Path, default):
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def dump_json(path: Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def read_state(path: Path, max_states: int) -> int:
    if not path.exists():
        return 0
    match = STATE_PATTERN.search(path.read_text(encoding="utf-8"))
    if not match:
        return 0
    return int(match.group(1)) % max_states


def collect_states(recipes: list[dict[str, str]], max_states: int) -> dict[str, int]:
    states: dict[str, int] = {}
    for recipe in recipes:
        path = ROOT / recipe["path"]
        states[recipe["path"]] = read_state(path, max_states)
    return states


def state_counts(states: dict[str, int], max_states: int) -> list[int]:
    counts = [0 for _ in range(max_states)]
    for value in states.values():
        counts[value] += 1
    return counts


def entropy(counts: list[int]) -> float:
    total = sum(counts)
    if total == 0:
        return 0.0
    score = 0.0
    for count in counts:
        if count == 0:
            continue
        p = count / total
        score -= p * math.log2(p)
    return score


def skew(counts: list[int]) -> int:
    return max(counts) - min(counts)


def build_file_content(app: str, role: str, state: int, state_data: dict[str, str]) -> str:
    cap = app.capitalize()
    label = state_data["label"]
    focus = state_data["focus"]
    guard = state_data["guard"]
    metric = state_data["metric"]
    style = state_data["style"]

    header = (
        f"# EVOLVER_STATE: {state}\n"
        '"""Autogenerated evolutionary module."""\n\n'
        f'APP_NAME = "{app}"\n'
        f'MODULE_ROLE = "{role}"\n'
        f'STATE_LABEL = "{label}"\n'
        f'FOCUS_VECTOR = "{focus}"\n'
        f'GUARD_RAIL = "{guard}"\n'
        f'QUALITY_METRIC = "{metric}"\n'
        f'DELIVERY_STYLE = "{style}"\n\n'
    )

    if role == "models":
        body = f"""from dataclasses import dataclass


@dataclass(slots=True)
class {cap}EvolutionModel:
    scope: str = APP_NAME
    state_label: str = STATE_LABEL
    focus_vector: str = FOCUS_VECTOR
    guard_rail: str = GUARD_RAIL


def snapshot() -> dict[str, str]:
    return {{
        "scope": APP_NAME,
        "state_label": STATE_LABEL,
        "focus_vector": FOCUS_VECTOR,
        "guard_rail": GUARD_RAIL,
        "quality_metric": QUALITY_METRIC,
    }}
"""
    elif role == "views":
        body = """def evolution_view() -> dict[str, str]:
    return {
        "app": APP_NAME,
        "role": MODULE_ROLE,
        "state": STATE_LABEL,
        "style": DELIVERY_STYLE,
        "metric": QUALITY_METRIC,
    }


def health_probe() -> str:
    return f"{APP_NAME}/{MODULE_ROLE}:{STATE_LABEL}"
"""
    elif role == "services":
        body = """def orchestrate(payload: dict[str, str]) -> dict[str, str]:
    merged = dict(payload)
    merged["app"] = APP_NAME
    merged["focus"] = FOCUS_VECTOR
    merged["guard"] = GUARD_RAIL
    merged["style"] = DELIVERY_STYLE
    return merged
"""
    elif role == "selectors":
        body = """def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
"""
    elif role == "tasks":
        body = """def run_task() -> str:
    return f"task:{APP_NAME}:{STATE_LABEL}:{QUALITY_METRIC}"
"""
    else:
        body = """def validate(packet: dict[str, str]) -> bool:
    required = ["app", "state"]
    if not all(key in packet for key in required):
        return False
    return packet["app"] == APP_NAME and packet["state"] != ""
"""

    return header + body


def ensure_seed(path: Path, app: str, role: str, matrix: list[dict[str, str]]) -> None:
    if path.exists():
        return
    path.write_text(build_file_content(app, role, 0, matrix[0]), encoding="utf-8")


def update_recipe(path: Path, app: str, role: str, matrix: list[dict[str, str]]) -> tuple[int, int]:
    max_states = len(matrix)
    current = read_state(path, max_states)
    next_state = (current + random.choice([-1, 1])) % max_states
    path.write_text(build_file_content(app, role, next_state, matrix[next_state]), encoding="utf-8")
    return current, next_state


def imbalance_after_move(counts: list[int], old_state: int, new_state: int) -> int:
    trial = list(counts)
    trial[old_state] -= 1
    trial[new_state] += 1
    return skew(trial)


def choose_transition(
    recipe: dict[str, str],
    states: dict[str, int],
    counts: list[int],
    runtime_state: dict,
    max_states: int,
) -> tuple[int, int, float]:
    path = recipe["path"]
    current = states[path]
    candidates = [((current - 1) % max_states), ((current + 1) % max_states)]

    touches = runtime_state.get("fileTouches", {})
    last_touched_step = int(touches.get(path, -1))
    tick = int(runtime_state.get("tick", 0))
    age_bonus = max(0.0, min(3.0, (tick - last_touched_step) / 10.0))
    total_files = max(1, len(states))
    target = total_files / max_states

    scarce_states = sorted(range(max_states), key=lambda idx: counts[idx])[: max(2, max_states // 4)]

    def circular_distance(src: int, dst: int) -> int:
        forward = (dst - src) % max_states
        backward = (src - dst) % max_states
        return min(forward, backward)

    scored: list[tuple[int, float]] = []
    current_skew = skew(counts)
    for nxt in candidates:
        projected = imbalance_after_move(counts, current, nxt)
        balancing_gain = float(current_skew - projected)
        rarity_bonus = float(max(counts) - counts[nxt]) / total_files
        pressure = (counts[current] - target) / total_files
        scarcity_pull = 0.0
        if scarce_states:
            best_current = min(circular_distance(current, x) for x in scarce_states)
            best_next = min(circular_distance(nxt, x) for x in scarce_states)
            scarcity_pull = float(best_current - best_next)
        noise = random.uniform(0.0, 0.35)
        score = balancing_gain * 2.2 + rarity_bonus * 2.6 + pressure * 2.0 + scarcity_pull * 1.3 + age_bonus + noise
        scored.append((nxt, score))

    scored.sort(key=lambda item: item[1], reverse=True)
    return current, scored[0][0], scored[0][1]


def choose_files(
    recipes: list[dict[str, str]],
    states: dict[str, int],
    counts: list[int],
    runtime_state: dict,
    count_min: int,
    count_max: int,
) -> list[dict[str, str]]:
    max_states = len(counts)
    drift = skew(counts)
    total_files = len(recipes)
    target = total_files / max_states

    dynamic_max = count_max
    if drift > max(2, total_files // max_states):
        dynamic_max = min(max(count_min, 2), count_max)

    pick_count = random.randint(count_min, dynamic_max)

    touches = runtime_state.get("fileTouches", {})
    tick = int(runtime_state.get("tick", 0))
    weighted: list[tuple[float, dict[str, str]]] = []

    for recipe in recipes:
        path = recipe["path"]
        current = states[path]
        age = tick - int(touches.get(path, -1))
        state_pressure = (counts[current] - target) / max(1, total_files)
        score = 1.0 + max(0, age) * 0.06 + state_pressure * 4.0 + random.uniform(0.0, 0.2)
        weighted.append((score, recipe))

    weighted.sort(key=lambda item: item[0], reverse=True)
    return [item[1] for item in weighted[:pick_count]]


def render_dashboard(
    matrix: list[dict[str, str]],
    recipes: list[dict[str, str]],
    after_states: dict[str, int],
    counts: list[int],
    after_counts: list[int],
    changes: list[dict[str, object]],
    history: list[dict[str, object]],
    dashboard_path: Path,
) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    before_entropy = entropy(counts)
    after_entropy = entropy(after_counts)
    before_skew = skew(counts)
    after_skew = skew(after_counts)
    recent = history[-10:]

    lines: list[str] = []
    lines.append("# Evolver Dashboard")
    lines.append("")
    lines.append(f"Last run: {now}")
    lines.append(f"Files changed this run: {len(changes)}")
    lines.append(f"Skew: {before_skew} -> {after_skew}")
    lines.append(f"Entropy: {before_entropy:.3f} -> {after_entropy:.3f}")
    lines.append("")
    lines.append("## State Distribution")
    lines.append("")
    lines.append("| State | Label | Before | After |")
    lines.append("|---|---|---:|---:|")
    for idx, meta in enumerate(matrix):
        lines.append(f"| {idx} | {meta['label']} | {counts[idx]} | {after_counts[idx]} |")

    lines.append("")
    lines.append("## App Distribution")
    lines.append("")
    lines.append("| App | Dominant State | Count |")
    lines.append("|---|---|---:|")
    app_buckets: dict[str, dict[int, int]] = {}
    for recipe in recipes:
        app = recipe["app"]
        state = after_states[recipe["path"]]
        app_buckets.setdefault(app, {})
        app_buckets[app][state] = app_buckets[app].get(state, 0) + 1
    for app, bucket in sorted(app_buckets.items()):
        dominant_state = max(bucket.items(), key=lambda item: item[1])[0]
        dominant_count = bucket[dominant_state]
        lines.append(f"| {app} | {matrix[dominant_state]['label']} ({dominant_state}) | {dominant_count} |")

    lines.append("")
    lines.append("## Role Distribution")
    lines.append("")
    lines.append("| Role | Dominant State | Count |")
    lines.append("|---|---|---:|")
    role_buckets: dict[str, dict[int, int]] = {}
    for recipe in recipes:
        role = recipe["role"]
        state = after_states[recipe["path"]]
        role_buckets.setdefault(role, {})
        role_buckets[role][state] = role_buckets[role].get(state, 0) + 1
    for role, bucket in sorted(role_buckets.items()):
        dominant_state = max(bucket.items(), key=lambda item: item[1])[0]
        dominant_count = bucket[dominant_state]
        lines.append(f"| {role} | {matrix[dominant_state]['label']} ({dominant_state}) | {dominant_count} |")

    lines.append("")
    lines.append("## This Run Changes")
    lines.append("")
    if not changes:
        lines.append("- No file transitions")
    else:
        for change in changes:
            lines.append(
                f"- `{change['path']}`: {change['from']} -> {change['to']} "
                f"({change['fromLabel']} -> {change['toLabel']}, score={change['score']:.3f})"
            )

    lines.append("")
    lines.append("## Recent History")
    lines.append("")
    if not recent:
        lines.append("- No history yet")
    else:
        for item in reversed(recent):
            stamp = item.get("timestamp", "unknown")
            changed = int(item.get("filesChanged", 0))
            drift = int(item.get("driftAfter", 0))
            lines.append(f"- {stamp}: changed={changed}, drift={drift}")

    dashboard_path.parent.mkdir(parents=True, exist_ok=True)
    dashboard_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Mutate 1-2 Django-like files by state transition")
    parser.add_argument("--count-min", type=int, default=1)
    parser.add_argument("--count-max", type=int, default=2)
    parser.add_argument("--history-limit", type=int, default=200)
    parser.add_argument("--dashboard", type=str, default=str(DASHBOARD_PATH))
    parser.add_argument("--seed", type=int, default=None)
    args = parser.parse_args()

    if args.seed is not None:
        random.seed(args.seed)

    recipes = load_json(RECIPES_PATH)
    matrix = load_json(MATRIX_PATH)
    runtime_state = load_json_or_default(RUNTIME_STATE_PATH, {"tick": 0, "fileTouches": {}})
    history = load_json_or_default(RUNTIME_HISTORY_PATH, [])

    for recipe in recipes:
        path = ROOT / recipe["path"]
        path.parent.mkdir(parents=True, exist_ok=True)
        ensure_seed(path, recipe["app"], recipe["role"], matrix)

    max_pick = min(args.count_max, len(recipes))
    min_pick = min(args.count_min, max_pick)

    max_states = len(matrix)
    before_states = collect_states(recipes, max_states)
    before_counts = state_counts(before_states, max_states)

    chosen = choose_files(
        recipes=recipes,
        states=before_states,
        counts=before_counts,
        runtime_state=runtime_state,
        count_min=min_pick,
        count_max=max_pick,
    )

    print("Evolution changes:")
    touches = runtime_state.setdefault("fileTouches", {})
    runtime_state["tick"] = int(runtime_state.get("tick", 0)) + 1
    tick = int(runtime_state["tick"])

    changes: list[dict[str, object]] = []
    mutable_counts = list(before_counts)

    for recipe in chosen:
        path = ROOT / recipe["path"]
        old_state, new_state, score = choose_transition(
            recipe=recipe,
            states=before_states,
            counts=mutable_counts,
            runtime_state=runtime_state,
            max_states=max_states,
        )
        path.write_text(
            build_file_content(recipe["app"], recipe["role"], new_state, matrix[new_state]),
            encoding="utf-8",
        )
        mutable_counts[old_state] -= 1
        mutable_counts[new_state] += 1
        touches[recipe["path"]] = tick
        changes.append(
            {
                "path": recipe["path"],
                "from": old_state,
                "to": new_state,
                "fromLabel": matrix[old_state]["label"],
                "toLabel": matrix[new_state]["label"],
                "score": score,
            }
        )
        print(f" - {recipe['path']}: {old_state} -> {new_state}")

    after_states = collect_states(recipes, max_states)
    after_counts = state_counts(after_states, max_states)

    history.append(
        {
            "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            "filesChanged": len(changes),
            "driftAfter": skew(after_counts),
            "entropyAfter": round(entropy(after_counts), 4),
            "changes": changes,
        }
    )
    history = history[-max(1, args.history_limit) :]

    dump_json(RUNTIME_STATE_PATH, runtime_state)
    dump_json(RUNTIME_HISTORY_PATH, history)
    render_dashboard(
        matrix=matrix,
        recipes=recipes,
        after_states=after_states,
        counts=before_counts,
        after_counts=after_counts,
        changes=changes,
        history=history,
        dashboard_path=Path(args.dashboard),
    )

    print(f"Balance skew: {skew(before_counts)} -> {skew(after_counts)}")
    print(f"Entropy: {entropy(before_counts):.3f} -> {entropy(after_counts):.3f}")


if __name__ == "__main__":
    main()
