# EVOLVER_STATE: 4
"""Autogenerated evolutionary module."""

APP_NAME = "catalog"
MODULE_ROLE = "selectors"
STATE_LABEL = "prune"
FOCUS_VECTOR = "noise reduction"
GUARD_RAIL = "duplicate filters"
QUALITY_METRIC = "delta precision"
DELIVERY_STYLE = "surgical"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
