# EVOLVER_STATE: 8
"""Autogenerated evolutionary module."""

APP_NAME = "accounts"
MODULE_ROLE = "selectors"
STATE_LABEL = "merge"
FOCUS_VECTOR = "workflow convergence"
GUARD_RAIL = "conflict shields"
QUALITY_METRIC = "merge stability"
DELIVERY_STYLE = "balanced"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
