# EVOLVER_STATE: 2
"""Autogenerated evolutionary module."""

APP_NAME = "accounts"
MODULE_ROLE = "selectors"
STATE_LABEL = "shape"
FOCUS_VECTOR = "query simplification"
GUARD_RAIL = "null-safe fallback"
QUALITY_METRIC = "query depth"
DELIVERY_STYLE = "measured"

def select_priority(candidates: list[dict[str, str]]) -> dict[str, str] | None:
    if not candidates:
        return None
    ranked = sorted(candidates, key=lambda item: item.get("metric", QUALITY_METRIC))
    return ranked[-1]
